services:
  postgres:
    image: postgres:15-alpine
    container_name: postgres
    restart: always
    ports:
      - 5433:5432
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: go_drive

  api:
    container_name: api
    restart: on-failure
    build: ./back-end
    ports:
      - 8080:8080
    env_file:
      - .env
    depends_on:
      - postgres

  spa:
    container_name: spa
    build: ./front-end
    volumes:
      - react-build:/var/www/html
    environment:
      - REACT_APP_API_URL=http://api:8080/ride/
    depends_on:
      - api

  nginx:
    container_name: nginx
    build: ./nginx
    ports:
      - 80:80
    volumes:
      - react-build:/var/www/html
    depends_on:
      - postgres
      - api
      - spa

volumes:
  postgres-data:
  react-build:
